### PR TITLE
correct bug on type str to float

### PR DESCRIPTION
**Pull request by jjehl**
The type is wrong which cause the test float < string to be always True in python 2 and to raise an error in python3.
A simple type conversion works fine for both python version.

### CODE REVIEW

**Comment by show0k** [comment]
Thanks for pointing the issue. However, I think we should fix the bug above in the code, the key should not never be a string.

**Comment by jjehl** [comment]
The lib for vrep need to be update because actually they are not fully compatible with the last release of vrep (3.3.2). This means some vrep functions cause a crash of pypot.

**Comment by jjehl** [comment]
Why not merging to have a fix to use the move recorder in python 3 until to correct above in the code ?

**Comment by jjehl** [comment]
So a solution is to convert the str to float on json.load with : 
```
for i in d['positions'].keys(): 
    d['positions'][float(i)] = d['positions'].pop(i)
```

in 

```
@classmethod
    def load(cls, file):
        """ Loads a :class:`~pypot.primitive.move.Move` from a json file. """
        d = json.load(file)
        return cls.create(d)

```

@show0k  @pierre-rouanet  do you agree this solution ?

**Comment by show0k** [comment]
Thank you for spotting  the issue and the investigation.
I fixed it in #237 in a cleaner way I think.

**Pull request closed without merging**
