### PR TITLE
Seed Robotics Hand

### PR DESCRIPTION
**Pull request by TheTrueCyprien**
We have been working with pypot and the [RH4D hand](http://www.seedrobotics.com/rh4d-ares-hand.html) by Seed Robotics. 
Certain functionalities such as force control of the hand are not supported by the current version of Pypot. 
Together with [Marcus Soll](https://github.com/Top-Ranger) we made the necessary changes to pypot to fully support the RH4D hands.
We believe that these changes could also benefit other users and we would like to merge these changes upstream.

### CODE REVIEW

**Comment by show0k** [comment]
Your hand looks interesting ! Did you do your own motor with a Dynamixel compatible firmware ?
I'll take time to review your code next week.

**Comment by pierre-rouanet** [comment]
Thanks a lot for your contribution! It's always nice to see Pypot used in various project!

I'll review and gladly integrate it! Thanks again :)

**Comment by TheTrueCyprien** [comment]
To avoid confusion, I'd like to clarify that we are not part of Seed Robotics. These modifications were done for a project that uses these hands. We are not the manufacturer.

**Comment by pierre-rouanet** [comment]
See #235 for modification.

**Pull request merged**
