### PR TITLE
modify motor/set/register to support led value

### PR DESCRIPTION
**Pull request by Tibo42**
modify file: server/snap.py to support led value ( off, red, green, yellow ) when use '/motor/<motor>/set/<register>/<value>

### CODE REVIEW

**Comment by pierre-rouanet** [comment]
Fixed by 1301319d535e01a71ccda215e20dbbf65446e430

**Comment by show0k** [comment]
You have to change it also [here](https://github.com/poppy-project/pypot/blob/1301319d535e01a71ccda215e20dbbf65446e430/pypot/server/snap.py#L136) which should be the only one called by Snap to set a register, and btw, add the make_tuple to [this line](https://github.com/poppy-project/pypot/blob/1301319d535e01a71ccda215e20dbbf65446e430/pypot/server/snap.py#L152) (this was my mistake).

**Comment by pierre-rouanet** [comment]
Is this covered by your commit on pypot: https://github.com/poppy-project/pypot/commit/020b90aed91921dbe034b20f643f2e43d2399fca?

Random idea of the day: It would be real cool to have unittest of the snap blocks (no I've no idea how to do that...)

**Comment by show0k** [comment]
Yep, sorry I forgot to update my comment. The issue can be close.
For test of Snap blocks... It would be great to have main blocks in js....

**Comment by show0k** [comment]
oe

**Comment by pierre-rouanet** [comment]
> For test of Snap blocks... It would be great to have main blocks in js....

Good point!

**Pull request closed without merging**
