### PR TITLE
Add utility to build package for all python versions and platforms

### PR DESCRIPTION
**Pull request by show0k**
usage for pypot:

``` bash
anaconda login --user poppy-project
./build_conda_packages.py poppy-project --force-convert --recipe-path ../conda.recipe/ 
```

### CODE REVIEW

**Comment by pierre-rouanet** [comment]
I've tried to add condo-build-all directly in ci. Does it sound good to you @show0k ?

**Comment by show0k** [comment]
If I understand, conda-build-all is efficiant for building a big list of recipes because it will check of cross dependencies for the building order, but here, my script build_conda_packages allow to make packages for windows osx and linux from a simple command which is more usefull for our usage, no ?

**Comment by pierre-rouanet** [comment]
They are doing pretty much the same thing no (calling condo-build a bunch of time)? At least that's how I understand it.

In such case I'm always tempted to use a more "out-of-the-box" tool.

**Comment by show0k** [comment]
No, "my script" call `conda build` for the specified package with all python version, and after call `conda convert` for building cross platform packages.
"conda-build-all" call only `conda build`with high level configurations.
I agree with you to use a more out of the box tool, but "conda-build-all" doesn't do the job I intended to do (dealing easily with cross platform packages).
The best solution should be to integrate the cross platform functionality on "conda-build-all".

**Comment by pierre-rouanet** [comment]
I missed the convert part. I guess we could also use appveyor to also generate the recipe for windows. 

Both would be ok for me.

**Pull request closed without merging**
