### PR TITLE
Add XL-320 baud rate

### PR DESCRIPTION
**Pull request by dschofie**
This PR is to address this issue: https://github.com/poppy-project/pypot/issues/226

### CODE REVIEW

**Comment by show0k** [comment]
Thanks, but we should also modify`baudrate_to_dxl`, isn't it ?
Could you also fix the [pep8 lint](https://travis-ci.org/poppy-project/pypot/jobs/316288578#L887)?

**Comment by jjehl** [comment]
And your changes break the compatibility with mx-28.

**Comment by dschofie** [comment]
@show0k I updated `baudrate_to_dxl` and checked the other models, they seem to have the same baud rate.

**Comment by show0k** [comment]
Looks perfect for me, thank you @dschofie !

**Pull request merged**
