### PR TITLE
Fix unpack values at startup

### PR DESCRIPTION
**Pull request by pierre-rouanet**
ping @show0k (first PR from [feuvert](http://www.feuvert.fr)...)

### CODE REVIEW

**Comment by show0k** [comment]
I should make it works. Question: is not more pythonic to do:
```python
try:
    positions, speeds, loads = zip(*values)
except ValueError:
    raise DxlError("Couldn't initialize pos/speed/load sync loop!")
```

**Comment by show0k** [comment]
And you have to do the same fix [here](https://github.com/poppy-project/pypot/blob/master/pypot/dynamixel/controller.py#L143), and add a logger.warning [here](https://github.com/poppy-project/pypot/blob/master/pypot/dynamixel/controller.py#L66).

**Comment by pierre-rouanet** [comment]
1. :+1: 
2. It's where it has been modified no? https://github.com/poppy-project/pypot/blob/fix-unpack-vlaues-at-startup/pypot/dynamixel/controller.py
3. :+1:

**Comment by show0k** [comment]
2. Yes, you're right, I copy paste link of an old message without looking.
1. & 3. Ok, but now it is now consistent ; catch the exception or look if values is not empty but don't do both.

**Pull request merged**
