### PR TITLE
[WIP] Prepare the version 3.0

### PR DESCRIPTION
**Pull request by pierre-rouanet**
This major version should include:
- [x] merge poppy-creature in pypot for simplicity and maintainability :  19f356cca5005885d546c305bacc07e0060069e3
- [x] a better mockup robot with a controller faking the movement of a real motor
- [x] <del>a clean and unified REST API</del>
- [x] <del>the possibility to run a controller in a separate process</del>
- [ ] include (if any) recent changes in master pypot and master poppy-creature

### CODE REVIEW

**Comment by damiencaselli** [comment]
Considering we are thinking of moving to websockets for performance reasons, I wonder if _a clean and unified REST API_ is still needed.

I wouldn't mind unifying web communication by only using WS and get rid of the ridiculous amount of APIs we have tailored so far. It would only then be up to the client to implement the WS communication, which is already [done](https://github.com/warmcat/libwebsockets) [in](https://github.com/cyderize/rust-websocket) [pretty](https://github.com/zaphoyd/websocketpp) [much](http://www.cliki.net/clws) [every](https://github.com/aaugustin/websockets) [language](https://github.com/daltoniam/Starscream).

Not to mention this is trivial to do in JS.

@pierre-rouanet @show0k WDYT?

**Comment by pierre-rouanet** [comment]
I definitely agree on the "ridiculous amount of APIs" and I would also add "undocumented".

I would personally not have any specific problems with what you suggest but maybe we should directly ask the poppy community (through the forum maybe?) if anyone would actually miss one of those APIs (and if yes, why). What do you think?

**Comment by pierre-rouanet** [comment]
The new web API has not been finished and is mostly abandoned at the moment. It won't be merged in this version. It is still available in the branch: https://github.com/poppy-project/pypot/tree/unified-REST-API

**Comment by pierre-rouanet** [comment]
The possibility to run a controller in a separate process has been abandoned as it was breaking lot of APIs and the result where not satisfying. 

The code can be found in the branches https://github.com/poppy-project/pypot/tree/separate-controller and https://github.com/poppy-project/pypot/tree/dynamixel-packet-forging-optimisation

**Comment by jjehl** [comment]
Great and why not making a beautiful documentation on how to use a websocket to control your robot ?

**Pull request merged**
