### PR TITLE
Dynamic instantiation support in from_config()

### PR DESCRIPTION
**Pull request by sonelu**
Created factory.py in pypot/utils to support dynamic instantiation of classes when reading the JSON file.

Now classes that can be created from JSON (ex.controllers, motors) do not need to be imported in the
config.py file, instead they only need to be registered with the factory (see the pypot/dynamixel/controller.py and pypot/dynamixel/motor.py).

This way you can define your own controller classes and motors within your project and, as long as they are registered with register_class the standard from_config function will still be able to instantiate them no matter if they are in the pypot model or not. This gives you moch more flexibility to define motors, sensors, controllers, etc. without the need to include them allways in the pypot library.

### CODE REVIEW

**Comment by sonelu** [comment]
The Travis failure is due to a warning in services_launcher.py that I have not changed. I guess it's OK to merge it.

`./pypot/creatures/services_launcher.py:178:1: W293 blank line contains whitespace
`

**Comment by show0k** [comment]
This seems awesome @sonelu ! Maybe could you make a short tutorial notebook to explain how to define and register your own controller/sensor, it could be useful for lot of users !

**Comment by sonelu** [comment]
@show0k I will certainly do that - I am using the current robot as an example. It uses a board that has 4 USB chains and with the current MetaController it starts approximately 27 threads, which is not ideal. I will have a dedicated controller that will merge some of the functionality from the existing controllers into one, thus simplifying the threads.

**Comment by show0k** [comment]
Aah, does it improve the performances ? I would be interested to see it !

**Comment by show0k** [comment]
Hi @sonelu !
Do you have any news from that simplified meta-controller ?

**Comment by sonelu** [comment]
@show0k sorry I have been caught up in a lot of other things and I haven't moved beyond a basic update of the standard BaseDxlController that removes the AngleLimitRegisterController.

What I'm looking now is to have the robot using ROS as simple as possible. It is very easy now to install ROS (core) on an ARM machine with Ubuntu which is brilliant.

**Pull request closed without merging**
