### PR TITLE
web app

### PR DESCRIPTION
**Pull request by louzar**
this is the first mock up, it show how the first version will look like please give us your comments:  https://moqups.com/louzar/QeoO8rtn

### CODE REVIEW

**Comment by pierre-rouanet** [comment]
NIce!

I have a question though. Is the fact that you directly put the *callback* inside the returned string a problem for other applications? I mean you also have to provide the javascript function here, right?

Would it be possible to separate both?

**Comment by louzar** [comment]
well, what I did is using jsonp instate of using json, in jsonp we have to start to returned string with the name of java script function , so that when the browser get that string it will call that java script function to process the returned data.
Why we are using jsonp ? it's because we are facing a cross domain problem
What's cross domain problem? it's when the html page and the restfull web service are not hosted on the same server. More details are here http://www.pureexample.com/jquery/cross-domain-ajax.html

**Comment by louzar** [comment]
btw, the existing web services can only read data of actual state of the robot, what about writing new web services to update that state for example make the robot make some move

**Comment by pierre-rouanet** [comment]
I understand what you are saying but my question is what about when you don't want to use the API though javascript? It would be nice to still have this possibility as well! For instance, I'm using this to remotely connect to the robot using a zmq socket.

For moving the robot, you can use the *POST /motor/\<motor_name>/register/\<register_name>/value.json* request.

**Comment by louzar** [comment]
I understand your pb, I have to think about how to make the server return json or jsonp depending on the client

**Comment by louzar** [comment]
I added new method named initJsonPlugin (see below) , this method is called on every request to initilize the json plugin.
Can somebody look at the code and review it, I'm not python expert, I feel my code could be better.

def initJsonPlugin(self):
       response_type = bottle.request.query.response_type
       if response_type is not None and response_type == "jsonp":
          jd = lambda s: "callback_("+json.dumps(s, cls=MyJSONEncoder)+")"
          self.app.install(bottle.JSONPlugin(json_dumps=jd))
       else:
          jd = lambda s: json.dumps(s, cls=MyJSONEncoder)
          self.app.install(bottle.JSONPlugin(json_dumps=jd))

**Comment by pierre-rouanet** [comment]
Great @louzar !

I guess a slightly more pythonic code could look like:
```python
def init_json_plugin(self):
    response_type = bottle.request.query.response_type

    if response_type == "jsonp":
        jd = lambda s: 'call_back_({})'.format(json.dumps(s, cls=MyJSONEncoder))
    else:
        jd = lambda s: json.dumps(s, cls=MyJSONEncoder)

    self.app.install(bottle.JSONPlugin(json_dumps=jd))
```

and if you wan't to go even further (I'm not sure here it's really better though):
```python

def init_json_plugin(self):
    response_type = bottle.request.query.response_type

    jd = lambda s: ('call_back_({})'.format(json.dumps(s, cls=MyJSONEncoder))
                    if response_type == "jsonp"
                    else json.dumps(s, cls=MyJSONEncoder))

    self.app.install(bottle.JSONPlugin(json_dumps=jd))
```

**Pull request closed without merging**
