### PR TITLE
update .gitignore for jupyter checkpoints and other missing unwanted files

### PR DESCRIPTION
**Pull request by show0k**

### CODE REVIEW

**Comment by matthieu-lapeyre** [comment]
the ignore .xml seems pretty strong to me.

**Comment by show0k** [comment]
Perhaps, I hesitated before adding it. You can always add a file with -f argument. It just remove potentially unwanted files when we add directories.

**Comment by pierre-rouanet** [comment]
Yeah I agree with @matthieu-lapeyre. 

I guess a better solution would be to have the snap file in a separate folder.

**Comment by show0k** [comment]
Ok, good idea for the Snap! files. I'll update it today.

**Comment by show0k** [comment]
I removed xml file from .gitignore, easier...

**Pull request merged**
