### PR TITLE
Update find_local_ip to make it more generic

### PR DESCRIPTION
**Pull request by show0k**

### CODE REVIEW

**Comment by pierre-rouanet** [comment]
This version was not working for Gilles #education. It was only find localhost IP.

What was working, was to directly ask to find the IP of a host:

```python
import socket
print(socket.gethostbyname_ex('harry.local'))
```

**Comment by pierre-rouanet** [comment]
I've modified your code to choose the host. On my computer it does work as intended:

```python
In [3]: find_host_ip()
Out[3]: '172.20.10.2'

In [4]: find_host_ip('Mundaka.local')
Out[4]: '172.20.10.2'
```

**Comment by pierre-rouanet** [comment]
@show0k 

I would like to close this issue. But before that we still have to add a snap block automatically getting the IP from the host. I'm suggesting something like: 

screen shot 2016-03-09 at 12 11 37

Any better solution?

**Comment by show0k** [comment]
I have to test, but I feel that every blocks in the project are executed at startup, so the automatic modification of the ip in the project don't work. If this is right, we could make a block like this one, but the better solution is to not put in the executable zone of Snap.

**Comment by show0k** [comment]
This has broke the Snap URL API, the <host> after /ip/ should be optional not mandatory, no ?

**Comment by pierre-rouanet** [comment]
```python
 @self.app.get('/ip/<host>')
 def get_ip(host=None):
     return find_host_ip(host)
```

It should already be the case, no?

**Comment by show0k** [comment]
screen shot 2016-03-15 at 20 11 48
I took your example and add some things. Any other things to add on Snap ?

**Pull request merged**
