### PR TITLE
Support for Herkulex servos and combination with Dynamixel servos in a single robot

### PR DESCRIPTION
**Pull request by rml4o**
The Herkulex code follows the same structure as the one for Dynamixel servos, but is completely independent.

Only the 'robot/config.py' needs to be changed out of the existing code.

Servo / OS setup:
    - Servos baudrates should be set to 115,200 (e.g. with HerkulexManager)
    - It is also strongly advised to reduce the FTDI latency timer to 1ms (vs 16ms by default) in the port settings of your OS

Main outstanding points:
    - tweak the mechansim that sends / receives packets (e.g. via shared queue ?) in order to reduce latency with the FTDI USB-to-serial port. At the moment up to 6 servos can run at 50Hz. 
    - improve handling of long playtimes  (>  2.8s)
    - add the equivalent of the "goal_speed" function
    - and quite a few things here and there - this is still WIP!

### CODE REVIEW

**Comment by matthieu-lapeyre** [comment]
@rml4o why did you close this pull-request ?

**Comment by rml4o** [comment]
I did a few changes yesterday, was not sure whether they would be taken into account in the original pull request.

**Comment by rml4o** [comment]
well that was not really necessary, will re-open it

**Comment by matthieu-lapeyre** [comment]
PR compare your branch with our, if you add new commit to your branch it will be taken into account, no problem.

**Comment by matthieu-lapeyre** [comment]
We do not have Herkulex servo to try your code so just tell us when you think your PR is ready to merge.

**Comment by rml4o** [comment]
Thanks - it is stable now but I prefer to be on the safe side and have a little bit more mileage.
If you want to try it out, France Robotique sell an "easy starter kit" with everything to get started for just 48 euros!

**Pull request closed without merging**
